name: Moderate PR

on:
  issue_comment:
    types: [created]

permissions:
  pull-requests: write

jobs:
  pr_comment:
    runs-on: ubuntu-latest

    steps:
      - name: Initial Logging
        run: |
          echo "👮 Initializing moderation process..."
          echo "🔧 System: $(uname -a)"
          echo "✅ Environment loaded."

      - name: Get list of banned words
        run: |
          curl -L -o bad_words_list.txt https://raw.githubusercontent.com/leereilly/list-of-english-cliches/main/cliches.txt
          echo "🛑 Fetched list of banned phrases."

      - name: Hash banned words
        run: |
          head -n 5 bad_words_list.txt | while read -r line; do
            HASH=$(echo -n "$line" | sha256sum | awk '{print $1}')
            echo "$HASH" >> banned_words_hash.txt
          done
          echo "✅ Hashed banned words:"
          cat banned_words_hash.txt
          echo "SECURITY_HASH=sha256" >> $GITHUB_ENV

      - name: Check the comment
        env: 
          ORGANISATION: ${{ secrets.CTF_FLAG }}
          RUNNER_VER: ${{ secrets.RUNNER_VER }}
          SEVERITY_MODE: ${{ secrets.SEVERITY_MODE }}
          RETENTION_PERIOD: ${{ secrets.RETENTION_PERIOD }}
        id: check_comment
        run: |
          echo "📝 Comment body:"
          echo "${{ github.event.comment.body }}"

          COMMENT_HASH=$(echo -n "${{ github.event.comment.body }}" | sha256sum | awk '{print $1}')
          echo "🔐 SHA256 hash of comment: $COMMENT_HASH"

          COMMENT_SAFE='true'
          while read -r BANNED_HASH; do
            if [[ "$COMMENT_HASH" == "$BANNED_HASH" ]]; then
              echo "🚨 Comment contains banned word!"
              COMMENT_SAFE='false'
              break
            fi
          done < banned_words_hash.txt

          echo "✅ Is comment safe? $COMMENT_SAFE"

          echo "COMMENT_SAFE=$COMMENT_SAFE" >> $GITHUB_ENV

      - name: Delete PR Comment (if flagged)
        if: env.COMMENT_SAFE == 'false'
        uses: actions/github-script@v7.0.1
        with:
          script: |
            const repo = context.payload.repository.name;
            const owner = context.payload.repository.owner.login;
            const comment_id = context.payload.comment.id;

            if (!comment_id) {
              console.log("❌ Comment ID is undefined. Skipping deletion.");
              return;
            }

            await github.rest.issues.deleteComment({
              owner,
              repo,
              comment_id,
            });

            console.log("🧹 Deleted offensive comment.")

      - name: Encode and store secret flag (CTF)
        env:
          FLAG: ${{ secrets.CTF_FLAG }}
        run: |
          echo "🔐 Encoding secret flag (CTF)..."
          echo -n "$FLAG" | base64 > encoded_flag.txt
          echo "✅ Flag encoded and stored in encoded_flag.txt"

          echo "👀 Flag length: ${#FLAG}"
          echo "🐙 GitHub will mask the actual secret value!"
